services:
    redis:
        image: redis:7-alpine
        restart: unless-stopped
        command: redis-server --appendonly yes
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - redis-data:/data

    backend:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            redis:
                condition: service_healthy
        env_file:
            - .env
        restart: unless-stopped
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules

    worker:
        build: .
        command: node src/workers/auction.worker.js
        depends_on:
            redis:
                condition: service_healthy
        env_file:
            - .env
        restart: unless-stopped
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules

volumes:
    redis-data:
